<?php
return array(
	'flat_type'=>array(
		1 => 'both',
		2 => 'separate',
		3 => 'both',
		4 => 'combined',
		38 => 'both',
		40 => 'separate',
	),
	'bathrooms_sep'=>array(
		1 => '0',
		2 => '1',
	),
	'bathrooms_comb'=>array(
		3 => '1',
		4 => '2',
		5 => '3',
		6 => '4',
		7 => '5',
	),
	'refuse_chute'=>array(
		1 => '0',
		2 => '0',
		3 => '1',
	),
	'gcn_list_view_from_window'=>array(
		2 => 'yard',
		3 => 'street',
		4 => 'yard',
		5 => 'yardAndStreet',
		6 => 'yard',
		7 => 'yard',
		8 => 'yard',
		9 => 'yardAndStreet',
		10 => 'yard',
		11 => 'yardAndStreet',
		12 => 'yard',
		13 => 'yardAndStreet',
		14 => 'yardAndStreet',
		15 => 'street',
		16 => 'yardAndStreet',
		17 => 'street',
		18 => 'yard',
		19 => 'yardAndStreet',
		20 => 'yardAndStreet',
		21 => 'yard',
		22 => 'yard',
		23 => 'yardAndStreet',
		24 => 'yardAndStreet',
		27 => 'yard',
		28 => 'street',
		30 => 'yard',
		33 => 'yardAndStreet',
		34 => 'street',
	),
	'gcn_list_balcony_l'=>array(
		56 => 2,
		59 => 3,
		52 => 1,
		4 => 1,
		54 => 1,
	),
	'gcn_list_balcony_b'=>array(
		61 => 3,
		55 => 2,
		57 => 4,
		2 => 1,
		52 => 1,
		53 => 1,
		58 => 1,
	),
	'gcn_list_repair'=>array(
		2 => 'no',
		3 => 'cosmetic',
		4 => 'euro',
		5 => 'cosmetic' ,
		6 => 'design' ,
	),
	'gcn_list_type_house'=>array(
		27 => 'panel',
		25 => 'panel',
		8 => 'panel',
		10 => 'panel',
		11 => 'panel',
		24 => 'panel',
		33 => 'panel',
		9 => 'panel',
		35 => 'monolith',
		6 => 'block',
		12 => 'panel',
		16 => 'wood',
		28 => 'brick',
		36 => 'wireframe',
		31 => 'monolithBrick',
		7 => 'brick',
		5 => 'panel',
		14 => 'brick',
		32 => 'monolith',
		26 => 'monolith',
		29 => 'panel',
		4 => 'stalin',
		20 => 'brick',
		21 => 'brick',
		3 => 'brick',
	),
	'gcn_list_type_house_s'=>array(
		8 => '137',
		9 => '606',
		10 => '504',
		11 => '504д',
		24 => '600.11',
		25 => '121',
		27 => '1.090.1',
		33 => '602',
	),
	'gcn_list_lift'=>array(
		2 => '1',
		4 => '2',
		5 => '3',
	),
	'type_reward'=>array(
		2 => 'percent',
		3 => 'fixed',
	),
	'gcn_list_phone'=>array(
		1 => 0,
		2 => 1,
		3 => 0,
	),
	'type_flat'=>array(
		2 => 'free',
		7 => 'alternative',
		8 => 'alternative',
		9 => 'alternative',
	),
	'gcn_parking'=>array(
		3 => 'multilevel',
		5 => 'roof',
		2 => 'ground',
		4 => 'open' ,
		6 => 'underground' ,
	),
	'gcn_list_object'=>array(
		2 => 'houseSale',
		3 => 'houseSale',
		4 => 'landSale' ,
		5 => 'cottageSale' ,
		6 => 'houseShareSale' ,
		7 => 'townhouseSale' ,
	),
	'gcn_list_country_type_property'=>array(
		2 => 'suburbanNonProfitPartnership',
		3 => 'individualHousingConstruction',
		4 => 'gardening' ,
		5 => 'farm' ,
		6 => 'privateFarm' ,
		7 => 'suburbanNonProfitPartnership' ,
		8 => 'industrialLand' ,
		9 => 'privateFarm' ,
	),
	'gcn_list_country_electro'=>array(
		1 => 0,
		2 => 0,
		3 => 1,
		4 => 1,
	),
	'gcn_list_country_water'=>array(
		1 => 0,
		2 => 1,
		3 => 1,
		4 => 1,
		5 => 0,
		6 => 1,
		7 => 1,
		8 => 1,
	),
	'gcn_list_country_wc'=>array(
		2 => '',
		3 => 'indoors',
		4 => 'indoors',
		5 => 'outdoors',
		6 => 'indoors',
	),
	'gcn_list_country_gas'=>array(
		1 => 0,
		2 => 0,
		3 => 0,
		4 => 1,
	),
	'gcn_list_farm_sewerage'=>array(
		1 => 0,
		2 => 1,
		3 => 1,
		4 => 0,
	),
	'gcn_list_country_interior'=>array(
		2 => 'cosmetic',
		3 => 'cosmetic',
		4 => 'cosmetic',
		5 => 'design',
		6 => 'cosmetic',
		7 => 'euro',
		8 => 'no',
	),
	'gcn_list_country_security'=>array(
		1 => 0,
		2 => 1,
		3 => 0,
	),
	'gcn_list_country_walls'=>array(
		2 => 'brick',
		3 => 'foamConcreteBlock',
		4 => 'wood',
		5 => 'boards',
		6 => 'boards',
		7 => 'foamConcreteBlock',
		8 => 'foamConcreteBlock',
		9 => 'foamConcreteBlock',
		10 => 'foamConcreteBlock',
		11 => 'wood',
		12 => 'wood',
		13 => 'aerocreteBlock',
		14 => 'wood',
	),
	'gcn_list_country_heat'=>array(
		2 => 'no',
		3 => 'stove',
		4 => 'centralGas',
		5 => 'fireplace',
		6 => 'diesel',
		7 => 'solidFuelBoiler',
		8 => 'electric',
		9 => '',
		10 => 'autonomousGas',
		11 => 'stove',
		12 => 'electric',
		13 => '',
	),
	'gcn_list_type_object_comm'=>array(
		1 => '',
		2 => 'buildingSale',
		3 => 'freeAppointmentObjectSale',
		5 => 'commercialLandSale' ,
		6 => 'freeAppointmentObjectSale' ,
		7 => 'freeAppointmentObjectSale' ,
		8 => 'buildingSale' ,
		9 => 'garageSale' ,
	),
	'gcn_list_comm_type_cond'=>array(
		2 => 'typical',
		3 => 'design',
		4 => 'cosmeticRepairsRequired',
		5 => 'majorRepairsRequired',
		7 => 'cosmeticRepairsRequired',
		8 => 'cosmeticRepairsRequired',
		9 => 'majorRepairsRequired',
	),
	'gcn_list_comm_type_enter'=>array(
		2 => 'separateFromYard',
		3 => 'separateFromStreet',
		4 => 'commonFromYard',
		6 => 'commonFromStreet',
		7 => 'commonFromStreet',
		23 => 'separateFromStreet',
	),

);



